### ISSUE TITLE
Hangup option playing OGM instead on Phone Line Rule

### ISSUE THREAD

**Issue by CMTeam2017** [CMTeam2017/CheckMate-UI---26Sep17#17] opened 2018-01-08 21:23 UTC

**Comment by lisacopeland** [comment] 2018-01-09 03:50
I need more info - can you please give me a  reproduction scenario?

**Comment by CMTeam2017** [comment] 2018-01-09 22:45
Setting the Hangup option on Inbound calls does not hangup.  It plays an OGM.

**Comment by lisacopeland** [comment] 2018-01-13 06:39
This is because the dropdown contains the first option as a default and will not allow the field to be empyt

**Comment by lisacopeland** [comment] 2018-01-14 07:34
This is now fixed - the user can now leave the drop down blank

**Closed by lisacopeland** 2018-01-14 07:34 UTC
